spring:
  profiles:
    active: local

logging:
  file:
    name: logs/webflux.log
    max-size: 50MB
    max-history: 2
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    org.springframework: INFO
    webflux: DEBUG


